CREATE DATABASE estudos;
CREATE TABLE Clientes(
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  cpf VARCHAR(45) NOT NULL,
  telefone VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
  );
  SELECT * FROM Clientes; 
  
